// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class RequisitoRF5TestIT {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void rF5() {
    driver.get("http://localhost:8080/fintech-war/");
    driver.manage().window().setSize(new Dimension(961, 818));
    driver.findElement(By.linkText("Inicio Sesión Administrador")).click();
    driver.findElement(By.id("index:user")).click();
    driver.findElement(By.id("index:user")).sendKeys("ponciano");
    driver.findElement(By.id("index:pass")).click();
    driver.findElement(By.id("index:pass")).sendKeys("ponciano");
    driver.findElement(By.cssSelector("#index\\3A botonIniciarSesion > .ui-button-text")).click();
    driver.findElement(By.linkText("Pooled")).click();
    driver.findElement(By.id("crearCuenta:firstname")).click();
    driver.findElement(By.id("crearCuenta:firstname")).sendKeys("767657575756");
    driver.findElement(By.id("crearCuenta:lastname")).click();
    driver.findElement(By.id("crearCuenta:lastname")).sendKeys("2232323");
    driver.findElement(By.id("crearCuenta:divisa")).click();
    driver.findElement(By.id("crearCuenta:divisa")).sendKeys("eur");
    driver.findElement(By.id("crearCuenta:identificacion")).click();
    driver.findElement(By.id("crearCuenta:identificacion")).sendKeys("63937528N");
    driver.findElement(By.cssSelector("#crearCuenta\\3AsaveBtn > .ui-button-text")).click();
  }
}
