// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class TESTR2TTestIT {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tESTR2() {
    driver.get("http://localhost:8080/fintech-war/");
    driver.manage().window().setSize(new Dimension(781, 652));
    driver.findElement(By.cssSelector("li:nth-child(5) b")).click();
    driver.findElement(By.id("index:user")).click();
    driver.findElement(By.id("index:user")).sendKeys("ponciano");
    driver.findElement(By.id("index:pass")).click();
    driver.findElement(By.id("index:pass")).sendKeys("ponciano");
    driver.findElement(By.id("index:botonIniciarSesion")).click();
    {
      WebElement element = driver.findElement(By.id("formExterior:submenuClientes"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("formExterior:listaClientes")).click();
    driver.findElement(By.xpath("formularioParaIndividuales:tablaConListaIndividuales:0:campoBotonModificar")).click();
    driver.findElement(By.id("form:Dirección1")).click();
    driver.findElement(By.id("form:Dirección1")).sendKeys("Madrid");
    driver.findElement(By.xpath("//button[@id=\'form:modificar\']/span")).click();
  }
}
