// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TESTTTestIT {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tESTR1() {
    driver.get("http://localhost:8080/fintech-war/");
    driver.manage().window().setSize(new Dimension(806, 818));
    driver.findElement(By.cssSelector("li:nth-child(5) b")).click();
    driver.findElement(By.id("index:user")).click();
    driver.findElement(By.id("index:user")).sendKeys("ponciano");
    driver.findElement(By.id("index:pass")).click();
    driver.findElement(By.id("index:pass")).sendKeys("ponciano");
    driver.findElement(By.cssSelector("#index\\3A botonIniciarSesion > .ui-button-text")).click();
  }
  @Test
  public void tESTR2() {
    driver.get("http://localhost:8080/fintech-war/");
    driver.manage().window().setSize(new Dimension(806, 818));
    driver.findElement(By.cssSelector("li:nth-child(5) b")).click();
    driver.findElement(By.id("index:user")).click();
    driver.findElement(By.id("index:user")).sendKeys("ponciano");
    driver.findElement(By.id("index:pass")).click();
    driver.findElement(By.id("index:pass")).sendKeys("ponciano");
    driver.findElement(By.cssSelector("#index\\3A botonIniciarSesion > .ui-button-text")).click();
    {
      WebElement element = driver.findElement(By.linkText("Clientes"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.linkText("Dar alta")).click();
    driver.findElement(By.id("f:daindi")).click();
    driver.findElement(By.id("DarAltaClienteAdministrador:Nombre_txt")).click();
    driver.findElement(By.id("DarAltaClienteAdministrador:Nombre_txt")).sendKeys("Felipe");
    driver.findElement(By.id("DarAltaClienteAdministrador:Apellidos_txt")).click();
    driver.findElement(By.id("DarAltaClienteAdministrador:Apellidos_txt")).sendKeys("Sanchez");
    driver.findElement(By.id("DarAltaClienteAdministrador:Identificacion_txt")).click();
    driver.findElement(By.id("DarAltaClienteAdministrador:Identificacion_txt")).sendKeys("123456789P");
    driver.findElement(By.id("DarAltaClienteAdministrador:Dirección_txt")).click();
    driver.findElement(By.id("DarAltaClienteAdministrador:Dirección_txt")).sendKeys("La Vinuela");
    driver.findElement(By.id("DarAltaClienteAdministrador:Ciudad_txt")).click();
    driver.findElement(By.id("DarAltaClienteAdministrador:Ciudad_txt")).sendKeys("Malaga");
    driver.findElement(By.id("DarAltaClienteAdministrador:CodigoPostal_txt")).click();
    driver.findElement(By.id("DarAltaClienteAdministrador:CodigoPostal_txt")).sendKeys("29712");
    driver.findElement(By.id("DarAltaClienteAdministrador:Pais_txt")).click();
    driver.findElement(By.id("DarAltaClienteAdministrador:Pais_txt")).sendKeys("Espana");
    driver.findElement(By.cssSelector("#DarAltaClienteAdministrador\\3A darAltaIndividual > .ui-button-text")).click();
  }
  @Test
  public void tESTR3() {
    driver.get("http://localhost:8080/fintech-war/");
    driver.manage().window().setSize(new Dimension(806, 818));
    driver.findElement(By.cssSelector("li:nth-child(5) b")).click();
    driver.findElement(By.id("index:user")).click();
    driver.findElement(By.id("index:user")).sendKeys("ponciano");
    driver.findElement(By.id("index:pass")).click();
    driver.findElement(By.id("index:pass")).sendKeys("ponciano");
    driver.findElement(By.cssSelector("#index\\3A botonIniciarSesion > .ui-button-text")).click();
    {
      WebElement element = driver.findElement(By.linkText("Clientes"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("f:lc")).click();
    driver.findElement(By.cssSelector("#formularioParaIndividuales\\3AtablaConListaIndividuales\\3A 1\\3A campoBotonModificar > .ui-button-text")).click();
    driver.findElement(By.id("form:Dirección1")).click();
    driver.findElement(By.id("form:Dirección1")).sendKeys("Mijas");
    driver.findElement(By.cssSelector(".ui-button-text:nth-child(1)")).click();
  }
  @Test
  public void tESTR4() {
    driver.get("http://localhost:8080/fintech-war/");
    driver.manage().window().setSize(new Dimension(806, 818));
    driver.findElement(By.cssSelector("li:nth-child(5) b")).click();
    driver.findElement(By.id("index:user")).click();
    driver.findElement(By.id("index:user")).sendKeys("ponciano");
    driver.findElement(By.id("index:pass")).click();
    driver.findElement(By.id("index:pass")).sendKeys("ponciano");
    driver.findElement(By.cssSelector("#index\\3A botonIniciarSesion > .ui-button-text")).click();
    {
      WebElement element = driver.findElement(By.linkText("Clientes"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("f:lc")).click();
    driver.findElement(By.cssSelector("#formularioParaIndividuales\\3AtablaConListaIndividuales\\3A 1\\3A campoBotonDarBaja2 > .ui-button-text")).click();
  }
  @Test
  public void tESTR5() {
    driver.get("http://localhost:8080/fintech-war/");
    driver.manage().window().setSize(new Dimension(806, 818));
    driver.findElement(By.linkText("Inicio Sesión Administrador")).click();
    driver.findElement(By.id("index:user")).click();
    driver.findElement(By.id("index:user")).sendKeys("ponciano");
    driver.findElement(By.id("index:pass")).click();
    driver.findElement(By.id("index:pass")).sendKeys("ponciano");
    driver.findElement(By.cssSelector("#index\\3A botonIniciarSesion > .ui-button-text")).click();
    {
      WebElement element = driver.findElement(By.linkText("Cuentas"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.linkText("Crear")).click();
    driver.findElement(By.linkText("Segregada")).click();
    driver.findElement(By.id("crearCuenta:firstname")).click();
    driver.findElement(By.id("crearCuenta:firstname")).sendKeys("ES19051999");
    driver.findElement(By.id("crearCuenta:lastname")).click();
    driver.findElement(By.id("crearCuenta:lastname")).sendKeys("1234");
    driver.findElement(By.id("crearCuenta:divisa")).click();
    driver.findElement(By.id("crearCuenta:divisa")).sendKeys("EUR");
    driver.findElement(By.id("crearCuenta:identificacion")).click();
    driver.findElement(By.id("crearCuenta:identificacion")).sendKeys("63937528N");
    driver.findElement(By.cssSelector("#crearCuenta\\3AsaveBtn > .ui-button-text")).click();
  }
  @Test
  public void tESTR6() {
    driver.get("http://localhost:8080/fintech-war/");
    driver.manage().window().setSize(new Dimension(806, 818));
    driver.findElement(By.cssSelector("li:nth-child(5) b")).click();
    driver.findElement(By.id("index:user")).click();
    driver.findElement(By.id("index:user")).sendKeys("ponciano");
    driver.findElement(By.id("index:pass")).click();
    driver.findElement(By.id("index:pass")).sendKeys("ponciano");
    driver.findElement(By.cssSelector("#index\\3A botonIniciarSesion > .ui-button-text")).click();
    {
      WebElement element = driver.findElement(By.linkText("Clientes"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("f:lc")).click();
    driver.findElement(By.cssSelector("#formularioParaEmpresas\\3AtablaConListaEmpresa\\3A 0\\3A botonAnadirAutorizado > .ui-button-text")).click();
    driver.findElement(By.id("form:j_idt38")).click();
    driver.findElement(By.id("form:j_idt38")).sendKeys("GEFRS45621");
    driver.findElement(By.id("form:j_idt40")).click();
    driver.findElement(By.id("form:j_idt40")).sendKeys("Escritura");
    driver.findElement(By.cssSelector(".ui-button-text:nth-child(1)")).click();
  }
  @Test
  public void tESTR7() {
    driver.get("http://localhost:8080/fintech-war/");
    driver.manage().window().setSize(new Dimension(804, 816));
    driver.findElement(By.cssSelector("li:nth-child(5) b")).click();
    driver.findElement(By.id("index:user")).click();
    driver.findElement(By.id("index:user")).sendKeys("ponciano");
    driver.findElement(By.id("index:pass")).click();
    driver.findElement(By.id("index:pass")).sendKeys("ponciano");
    driver.findElement(By.cssSelector("#index\\3A botonIniciarSesion > .ui-button-text")).click();
    {
      WebElement element = driver.findElement(By.linkText("Personas Autorizadas"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.linkText("Lista")).click();
    driver.findElement(By.cssSelector("#j_idt34\\3Aj_idt35\\3A 1\\3Aj_idt55 > .ui-button-text")).click();
    driver.findElement(By.id("form:j_idt42")).click();
    driver.findElement(By.id("form:j_idt42")).sendKeys("Campanillas");
    driver.findElement(By.cssSelector(".ui-button-text:nth-child(1)")).click();
  }
  @Test
  public void tESTR8() {
    driver.get("http://localhost:8080/fintech-war/");
    driver.manage().window().setSize(new Dimension(803, 816));
    driver.findElement(By.cssSelector("li:nth-child(5) b")).click();
    driver.findElement(By.id("index:user")).click();
    driver.findElement(By.id("index:user")).sendKeys("ponciano");
    driver.findElement(By.id("index:pass")).click();
    driver.findElement(By.id("index:pass")).sendKeys("ponciano");
    driver.findElement(By.cssSelector("#index\\3A botonIniciarSesion > .ui-button-text")).click();
    {
      WebElement element = driver.findElement(By.linkText("Cuentas"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.linkText("Lista")).click();
    driver.findElement(By.cssSelector("#j_idt55\\3Aj_idt56\\3A 0\\3Aj_idt74 > .ui-button-text")).click();
    driver.findElement(By.cssSelector("#MostarAutorizacion\\3Aj_idt55\\3A 1\\3A botonIniciarSesion > .ui-button-text")).click();
  }
  @Test
  public void tESTR9() {
    driver.get("http://localhost:8080/fintech-war/");
    driver.manage().window().setSize(new Dimension(806, 818));
    driver.findElement(By.linkText("Inicio Sesión Administrador")).click();
    driver.findElement(By.id("index:user")).click();
    driver.findElement(By.id("index:user")).sendKeys("ponciano");
    driver.findElement(By.id("index:pass")).click();
    driver.findElement(By.id("index:pass")).sendKeys("ponciano");
    driver.findElement(By.cssSelector("#index\\3A botonIniciarSesion > .ui-button-text")).click();
    {
      WebElement element = driver.findElement(By.linkText("Cuentas"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.linkText("Lista")).click();
    driver.findElement(By.cssSelector("#j_idt55\\3Aj_idt56\\3A 1\\3Aj_idt72 > .ui-button-text")).click();
  }
  @Test
  public void tESTR10() {
    driver.get("http://localhost:8080/fintech-war/");
    driver.manage().window().setSize(new Dimension(806, 818));
    driver.findElement(By.linkText("Inicio Sesión Cliente")).click();
    driver.findElement(By.id("index:user")).click();
    driver.findElement(By.id("index:user")).sendKeys("juan");
    driver.findElement(By.id("index:pass")).click();
    driver.findElement(By.id("index:pass")).sendKeys("juan");
    driver.findElement(By.cssSelector("#index\\3A botonIniciarSesion > .ui-button-text")).click();
  }
}
